### ISSUE TITLE
Clipping

### ISSUE THREAD

**Issue by midiguru** [AmalgamatedHarmonics/Prism#2]
I've used the Multiband Resonator, so I like where you're going with this. At the moment, anything higher than a very low setting of the main Q knob causes the filters to clip very badly. This happens even when the input trims are quite low. At the moment (release 1.0.1) it's just too finicky to be useful -- way too much chance of nasty distortion.

**Comment by jhoar** [comment]
Hi! Thanks for the feedback.

Trying to tame clipping is quite difficult, there are combinations of filter frequencies and Q which are really guaranteed to cause problems. Since I am using the original firmware but do not have a physical module, one of the puzzles is working out where the VCV port is behaving differently from the hardware and why. 

I am sure that the hardware will clip as well - it's clearly something which 4ms tries to help the user deal with.

So trust me, I'm working on it!

**Comment by midiguru** [comment]
1.0.2 sounds MUCH better! Thanks for working on it!

**Comment by AmalgamatedHarmonics** [comment]
Closed in 1.0.2
